MODEL_EXECUTABLE_DIRECTORY = "assets"
MODEL_EXECUTABLE_PERMISSIONS = 0o777

AWS_ACCESS_KEY_ID_ENV = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV = "AWS_SECRET_ACCESS_KEY"


VERSION_PREFIX = "versoes"
INPUTS_PREFIX = "ingest"
INPUTS_ECHO_PREFIX = "entradas"
OUTPUTS_PREFIX = "saidas"

RAW_DECK_FILE = "eco_deck.zip"
PROCESSED_DECK_FILE = "deck_processado.zip"
RAW_OUTPUTS_FILE = "saidas.zip"

EXECUTION_ID_FILE = "id.modelops"
STATUS_DIAGNOSIS_FILE = "status.modelops"
METADATA_FILE = "metadata.modelops"
SYNTHESIS_DIR = "sintese"

MPICH_PATH = "/usr/local/mpich-4.2.0/bin"
SLURM_PATH = "/opt/slurm/bin"
SLURM_SUBMISSION_REGEX_PATTERN = "Submitted batch job (\\d+)"

NEWAVE_MAX_TASKS_PER_NODE = 67

DEFAULT_SHELL_COMMAND_TIMEOUT = 10.0
JOB_CANCELLATION_TIMEOUT = 60.0

FILE_SIZE_LIMIT_FOR_HASHING_BYTES = 5242880  # 5 MB


# METADATA KEYS
METADATA_MODELOPS_ID = "modelops_id"
METADATA_MODEL_NAME = "model_name"
METADATA_MODEL_VERSION = "model_version"
METADATA_PARENT_PATH = "parent_path"
METADATA_PARENT_STARTING_DATE = "parent_starting_date"
METADATA_STUDY_STARTING_DATE = "study_starting_date"
METADATA_STUDY_NAME = "study_name"
METADATA_JOB_ID = "job_id"
METADATA_STATUS = "status"
METADATA_INPUT_FILES = "input_files"
METADATA_EXECUTION_SOURCE = "execution_source"

# EXECUTION SOURCE VALUES
EXECUTION_SOURCE_OFFLINE = "OFFLINE"
